apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devsecops-demo.fullname" . }}-config
  labels:
    {{- include "devsecops-demo.labels" . | nindent 4 }}
data:
  application.properties: |
    # Default application properties
    logging.level.root={{ .Values.env.LOG_LEVEL }}
    logging.file.name=/app/logs/application.log
    server.port=8080
