apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devsecops-demo.fullname" . }}-file-config
  labels:
    {{- include "devsecops-demo.labels" . | nindent 4 }}
data:
  config.properties: |-
{{ .Files.Get "files/config.properties" | indent 4 }}
