pipeline:
  name: mvn-java-app-ci
  identifier: mvnjavaappci
  projectIdentifier: revanthcstesting
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.revanthplayground
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: Run_1
                  spec:
                    connectorRef: public
                    image: maven:3.9-eclipse-temurin-11
                    shell: Sh
                    command: |-
                      cd simple-java-app/
                      mvn clean package -DskipTests
                    resources:
                      limits:
                        memory: 100Mi
                        cpu: "0.2"
              - parallel:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: revanthdocker
                        repo: revanthharness/demo-java-app
                        tags:
                          - "<+<+pipeline.triggerType> == \"MANUAL\" ? \"dev-\" + <+pipeline.sequenceId> : <+expression.isUnresolved(<+trigger.tag>)>?<+codebase.shortCommitSha>: <+trigger.tag> >"
                        caching: true
                        dockerfile: simple-java-app/Dockerfile
                        resources:
                          limits:
                            cpu: "0.5"
                  - step:
                      identifier: publish_plugin
                      type: Plugin
                      name: git release
                      spec:
                        connectorRef: public
                        image: plugins/github-release
                        settings:
                          base_url: https://github.com/revanth-traceable
                          api_key: <+secrets.getValue("github-pat")>
                          files: simple-java-app/target/*
                      when:
                        stageStatus: Success
                        condition: "false"
              - step:
                  type: Run
                  name: helm-package
                  identifier: helmpackage
                  spec:
                    connectorRef: public
                    image: alpine/helm:3.11.1
                    shell: Bash
                    command: |-
                      cd simple-java-app/helm/devsecops-demo
                      BASE_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
                      TAG="<+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].tag>"

                            if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                              CHART_VERSION=${TAG}
                            else
                              # For all non-tagged builds
                              CHART_VERSION="${BASE_VERSION}-${TAG}"
                            fi

                      # Update the Chart.yaml with this version
                      sed -i "s/version: ${BASE_VERSION}/version: ${CHART_VERSION}/" Chart.yaml



                      helm registry login pkg.harness.io -u sai.veera@harness.io -p <+secrets.getValue("har-helm-token")>
                      helm package .
                      helm push devsecops-demo-${CHART_VERSION}.tgz oci://pkg.harness.io/sl32ke39qekmavwtgmagow/har-helm-repo
              - stepGroup:
                  name: scan
                  identifier: scan
                  steps:
                    - parallel:
                        - step:
                            type: Grype
                            name: Grype_1
                            identifier: Grype_1
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: container
                                detection: auto
                              advanced:
                                log:
                                  level: info
                                fail_on_severity: none
                              resources:
                                limits:
                                  memory: 500Mi
                                  cpu: "0.5"
                              privileged: true
                              image:
                                type: docker_v2
                                tag: <+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].tag>
                                name: <+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].imageName>
                        - step:
                            type: Semgrep
                            name: Semgrep_1
                            identifier: Semgrep_1
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
                              resources:
                                limits:
                                  memory: 500Mi
                                  cpu: "0.5"
              - stepGroup:
                  name: scs
                  identifier: scs
                  steps:
                    - parallel:
                        - step:
                            type: SscaOrchestration
                            name: SBOM Orchestration_1
                            identifier: SBOMOrchestration_1
                            spec:
                              mode: generation
                              tool:
                                type: Syft
                                spec:
                                  format: spdx-json
                              source:
                                type: docker
                                spec:
                                  connector: revanthdocker
                                  image: <+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].imageName>:<+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].tag>
                              attestation:
                                type: cosign
                                spec:
                                  privateKey: artifact-signing-pub
                                  password: reavnth-artifact-signing
                              sbom_drift:
                                base: last_generated_sbom
                              resources:
                                limits:
                                  memory: 500Mi
                                  cpu: "0.5"
                        - step:
                            type: SscaArtifactSigning
                            name: Artifact Signing_1
                            identifier: ArtifactSigning_1
                            spec:
                              source:
                                type: docker
                                spec:
                                  connector: revanthdocker
                                  image: <+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].imageName>:<+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].tag>
                              signing:
                                type: cosign
                                spec:
                                  private_key: artifact-signing-pub
                                  password: reavnth-artifact-signing
                              uploadSignature:
                                upload: true
                        - step:
                            type: provenance
                            name: SLSA Generation_1
                            identifier: SLSAGeneration_1
                            spec:
                              source:
                                type: docker
                                spec:
                                  connector: revanthdocker
                                  repo: <+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].imageName>:<+pipeline.stages.ci.spec.execution.steps.BuildAndPushDockerRegistry_1.artifact_BuildAndPushDockerRegistry_1.stepArtifacts.publishedImageArtifacts[0].tag>
                              attestation:
                                type: cosign
                                spec:
                                  private_key: artifact-signing-pub
                                  password: reavnth-artifact-signing
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
