pipeline:
  name: test-gc
  identifier: testgc
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: testt
                  identifier: testt
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: tetsnew
        identifier: tetsnew
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Container
                  name: Container_1
                  identifier: Container_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    command: ls
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: testdelegate
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables: {}
                  timeout: 1m 40s
              - stepGroup:
                  name: test
                  identifier: test
                  steps:
                    - step:
                        type: Container
                        name: Container_2
                        identifier: Container_2
                        spec:
                          connectorRef: account.harnessImage
                          image: docker:dind
                          command: ls
                          shell: Sh
                          infrastructure:
                            type: KubernetesDirect
                            spec:
                              connectorRef: testdelegate
                              namespace: default
                              resources:
                                limits:
                                  cpu: "0.5"
                                  memory: 500Mi
                              annotations: {}
                              labels: {}
                              containerSecurityContext:
                                capabilities:
                                  drop: []
                                  add: []
                              nodeSelector: {}
                          reports:
                            type: JUnit
                            spec:
                              paths: []
                          outputVariables: []
                          envVariables: {}
                        timeout: 1m 40s
          environment:
            environmentRef: test
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
        tags: {}
