pipeline:
  name: cs-playground
  identifier: csplayground
  projectIdentifier: revanthcstesting
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.revanthplayground
        build: <+input>
  stages:
    - stage:
        name: gobuild
        identifier: gobuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: revanthdocker
                    repo: revanthharness/hello-world-go-ci
                    tags:
                      - <+trigger.commitSha>
                    caching: true
                    dockerfile: hello-world/Dockerfile
    - stage:
        name: scan image
        identifier: scan_image
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Grype
                  name: Grype_1
                  identifier: Grype_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    connectorRef: revanthdocker
                    image:
                      type: docker_v2
                      tag: <+trigger.commitSha>
                      name: revanthharness/hello-world-go-ci
              - step:
                  type: SscaOrchestration
                  name: SBOM Orchestration_1
                  identifier: SBOMOrchestration_1
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: docker
                      spec:
                        connector: revanthdocker
                        image: revanthharness/hello-world-go-ci:<+trigger.commitSha>
                    attestation:
                      type: cosign
                      spec:
                        privateKey: artifact-signing-pub
                        password: reavnth-artifact-signing
                    sbom_drift:
                      base: last_generated_sbom
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    connectorRef: revanthdocker
                    image:
                      type: docker_v2
                      tag: <+trigger.commitSha>
                      name: revanthharness/hello-world-go-ci
                    sbom:
                      generate: false
                      format: spdx-json
              - step:
                  type: SscaArtifactSigning
                  name: Artifact Signing_1
                  identifier: ArtifactSigning_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: revanthdocker
                        image: revanthharness/hello-world-go-ci:<+trigger.commitSha>
                    signing:
                      type: cosign
                      spec:
                        private_key: artifact-signing-pub
                        password: reavnth-artifact-signing
                    uploadSignature:
                      upload: true
              - step:
                  type: SscaArtifactVerification
                  name: Artifact Verification_1
                  identifier: ArtifactVerification_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: revanthdocker
                        image: revanthharness/hello-world-go-ci:<+trigger.commitSha>
                    verifySign:
                      type: cosign
                      spec:
                        public_key: artifact-pub
              - step:
                  type: SscaEnforcement
                  name: SBOM Policy Enforcement_1
                  identifier: SBOMPolicyEnforcement_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: revanthdocker
                        image: revanthharness/hello-world-go-ci:<+trigger.commitSha>
                    verifyAttestation:
                      type: cosign
                      spec:
                        publicKey: artifact-pub
                    policy:
                      policySets:
                        - policy_set_sbom_allow_and_deny_list_04_30_16_48
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
    - stage:
        name: scanning code
        identifier: scanning_cide
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
