apiVersion: v2
name: devsecops-demo
description: A Helm chart for the DevSecOps Demo Java Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - java
  - devsecops
maintainers:
  - name: DevOps Team
    email: devops@example.com
