# Production values for devsecops-demo
# This is a YAML-formatted file.

replicaCount: 3

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

# Java specific
javaOpts: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"

# Environment variables
env:
  LOG_LEVEL: "WARN"

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# For better security in production
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
