# Production values for devsecops-demo
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: <+artifact.imagePath>
  pullPolicy: IfNotPresent
  tag: <+artifact.tag>

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

# Java specific
javaOpts: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"

# Environment variables
env:
  LOG_LEVEL: "WARN"

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 2

# For better security in production
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
