pipeline:
  name: looping-test
  identifier: loopingtest
  projectIdentifier: revanthcstesting
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-loop
        identifier: testloop
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo this is <+strategy.identifierPostFix>

                      echo <+pipeline.stages.testloop.spec.execution.steps.Run_1<+strategy.identifierPostFix>.name>
                    outputVariables:
                      - name: test_output
                        type: String
                        value: hi
        strategy:
          parallelism: 3
